name: Download and Upload Release

on:
  workflow_dispatch:  # Jalankan manual dari GitHub UI

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          url="https://phoenixnap.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/HyperOS-STABLE-RELEASES/HyperOS2.0/xiaomi.eu_ONYX_OS2.0.214.0.VOLCNXM_15.zip?viasf=1"   # Ganti dengan URL file kamu
          output="downloads/xiaomi.eu_ONYX_OS2.0.214.0.VOLCNXM_15.zip"          # Nama file hasil download

          mkdir -p $(dirname "$output")
          wget -O "$output" "$url"
          
      - name: Create tag
        run: |
          tag="v$(date +'%Y%m%d-%H%M')"
          echo "tag=$tag" >> $GITHUB_ENV
          git tag $tag
          git push origin $tag

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.tag }}
          name: "Release ${{ env.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload asset to Release
        uses: softprops/action-gh-release@v2
        with:
          files: downloads/xiaomi.eu_ONYX_OS2.0.214.0.VOLCNXM_15.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
